### ISSUE TITLE
Script not working on MacOSX Yosemite

### ISSUE THREAD

**Issue by anshulsolanki89** [chrisballinger/Opus-iOS#1]
Hi Chris I am trying to build opus Library for 64 bit support. Currently I have Xcode6 installed on my system whenever I run this script it gives me these errors 
Using opus-1.1.tar.gz
Building without ccache
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/anshul/Opus-iOS-master/build/src/opus-1.1':
configure: error: C compiler cannot create executables
See`config.log' for more details

Here is the output of my gcc --version  command
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

Please guide me whats going wrong.

Thanks

**Comment by 9cat** [comment]
any update for the iOS 64bit  support? we need it.
