### ISSUE TITLE
Error using newest OPUS version

### ISSUE THREAD

**Issue by quappi** [chrisballinger/Opus-iOS#4]
When using Opus 1.1.2 I am getting the following error while running the script:

```
#error Cannot build libopus with -ffast-math unless FLOAT_APPROX is defi...
 ^
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [celt/celt_decoder.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [celt/celt.lo] Error 1
make[2]: *** [celt/bands.lo] Error 1
1 error generated.
make[2]: *** [celt/celt_encoder.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by Tylerian** [comment]
Check my pull request in order to fix this issue.

**Comment by quappi** [comment]
I can confirm that this fix works. Please accept the pull request @chrisballinger 
Thanks @Tylerian for sharing!

**Comment by zeeshanecosmob** [comment]
this is not the proper solution. what if i want --enable-fixed-point instead --enable-float-approx. The issue will remain the same.
